# For use in mybinder.org
FROM andrewosh/binder-base

MAINTAINER Leonardo Uieda <leouieda@gmail.com>

USER root

USER main

# Copy from the Dockerfile generated by binder to create and activate the conda
# environment.
ADD environment.yml environment.yml
RUN conda env create -n binder
RUN echo "export PATH=/home/main/anaconda2/envs/binder/bin/:/home/main/anaconda3/envs/binder/bin/:$PATH" >> ~/.binder_start
RUN conda install -n binder jupyter
RUN /bin/bash -c "source activate binder && jupyter kernelspec install-self --user"
# To get around the new default authentication in Jupyter
RUN /bin/bash -c "source activate binder && jupyter notebook --NotebookApp.token=''"
